# only tagged build/deploy
if: tag IS present

sudo: required
language: node_js
node_js:
  - lts/*

env:
  global:
    - SOURCE=dist/bundle.zip
    - EXTENSION_ID=cjphebojlojkmfgclckgpnjdkgkfkmkf
    - CLIENT_ID=$WS_CLIENT_ID
    - CLIENT_SECRET=$WS_CLIENT_SECRET
    - REFRESH_TOKEN=$WS_REFRESH_TOKEN

before_script:
  - npm i -g chrome-webstore-upload-cli
  - npm i
  - npm run bundle

script:
  - webstore upload --source $SOURCE --extension-id $EXTENSION_ID --client-id $CLIENT_ID --client-secret $CLIENT_SECRET --refresh-token $REFRESH_TOKEN --auto-publish
